### ISSUE TITLE
Wrong link to raw checklist-en file

### ISSUE THREAD

**Issue by sdarmofal** [vintasoftware/devchecklists-template#6]
Link in first section of checklist-en.md that should redirect to raw file is https://raw.githubusercontent.com/vintasoftware/devchecklists-template/master/checklist-us.md but it should be https://raw.githubusercontent.com/vintasoftware/devchecklists-template/master/checklist-en.md.

**Comment by felipefarias** [comment]
Thanks @sdarmofal! This issue was fixed!
